/// Please use the following editor setup for this file:

// Tab size=2; Tabs as spaces; Clean up trailing whitepsace
// 'make proto' will run clang-format to fix formatiing
syntax = "proto3";
package watchdog;

option go_package = "github.com/binuud/watchdog/gen/go/v1/watchdog";

// import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";


message GitProject {

  // unique UUID for each project
  string uuid = 1;

  // project name
  string name = 2;   

  // project path, relative to home directory
  string path = 3;   

  // small description about the project
  string description = 4;

  // project org
  string org = 5; 

  // the github, gitlab project url 
  string projecturl = 6;

  // github repo upstream path
  string remoteurl = 7;

  // default github user for this project
  string user = 8;

  enum ProjectStatus {
    IGNORE_PROJECT_STATUS = 0;
    // read status, project is live
    ACTIVE = 1; 
    // project is not live
    INACTIVE = 2; 
    // project is not active, use data from cached always
    ARCHIVE = 3;  
  }

  ProjectStatus status = 10;

}

// Represents the overall status of the Git repository.
message GitProjectStatus {

  // e.g., "master"
  string branch_name = 1;     
  
  // e.g., "origin/master"
  string upstream_branch = 2;   
  
  // Number of commits ahead of upstream
  int32 ahead_count = 3;     
  
  // Number of commits behind upstream
  int32 behind_count = 4;    
  
  // True if the working tree is clean
  bool is_clean = 5;   
  
  // numbers of modified, unstaged, untracked, ignored files
  int64 num_modified = 11;
  int64 num_unstaged = 12;
  int64 num_untracked = 13;
  int64 num_ignored = 14;
  int64 num_stashes = 15;

  int64 num_pr_open = 16;
  int64 num_issues_open = 17;
  
  // Changes to be committed
  repeated FileStatus staged = 21;   
  
  // Changes not staged for commit
  repeated FileStatus unstaged = 22;  

  // Paths of completely new, untracked files
  repeated string untracked = 23; 
  
  // Paths explicitly ignored (if requested)
  repeated string ignored = 24;   

  // common ancestor in local and remote branch
  // when remote goes ahead to the local branch
  string common_ancestor = 30;    


}


// Represents an individual file change state.
message FileStatus {

  // The file path relative to repository root
  string path = 1; 
  
  // Only populated if the file was renamed or copied
  string old_path = 2;            
  
  // The exact status action performed on the file
  enum StatusCode {
    STATUS_CODE_UNSPECIFIED = 0;
    MODIFIED = 1;
    ADDED = 2;
    DELETED = 3;
    RENAMED = 4;
    COPIED = 5;
    // e.g., regular file changed to a symlink
    TYPE_CHANGED = 6;   
    // Merge conflict state          
    UNMERGED = 7;                 
  }
  
  StatusCode status = 3;

}

// used for persisting git project information
message GitProjectRow {

  GitProject project = 1;
  GitProjectStatus status = 2;
  google.protobuf.Timestamp createdAt = 11;

}