/// Please use the following editor setup for this file:

// Tab size=2; Tabs as spaces; Clean up trailing whitepsace
// 'make proto' will run clang-format to fix formatiing
syntax = "proto3";
package watchdog;

option go_package = "github.com/binuud/watchdog/gen/go/v1/watchdog";

import "google/api/annotations.proto";
import "v1/watchdog/git.proto";

service Git {
  rpc Health(GitHealthRequest) returns (GitHealthResponse) {
    option (google.api.http) = {
      get : "/v1/git/health"
    };
  }
}

message GitHealthRequest {}

message GitHealthResponse {
  int64 createdAt = 1;
  // number of projects being watched
  int64 num_projects = 2;
  enum HealthStatus {
    HealthStatusIgnore = 0;
    Active = 1;
    Error = 2;
  }
  HealthStatus status = 3;
}