name: MyDomains
refreshinterval: 86400
domains:
    - uuid: ""
      name: www.google.com
      endpoints:
        - https://www.google.com
    - uuid: ""
      name: www.gmail.com
      endpoints:
        - https://www.gmail.com
    - uuid: ""
      name: www.apple.com
      endpoints:
        - https://www.apple.com
    - uuid: ""
      name: www.dronasys.com
      endpoints:
        - https://www.dronasys.com
   
