openapi: 3.1.0
info:
  title: ""
  version: ""
paths:
  /v1/watchdog/get:
    get:
      operationId: get
      parameters:
        - name: name
          in: query
          schema:
            type: string
        - name: uuid
          in: query
          schema:
            type: string
      responses:
        "200":
          description: watchdog.WatchDog.Get response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResponse'
  /v1/watchdog/getAll:
    get:
      operationId: getAll
      responses:
        "200":
          description: watchdog.WatchDog.GetAll response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllResponse'
  /v1/watchdog/getDetails:
    get:
      operationId: getDetails
      parameters:
        - name: name
          in: query
          schema:
            type: string
        - name: uuid
          in: query
          schema:
            type: string
      responses:
        "200":
          description: watchdog.WatchDog.GetDetails response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDetailsResponse'
  /v1/watchdog/health:
    get:
      operationId: health
      responses:
        "200":
          description: watchdog.WatchDog.Health response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /v1/watchdog/reload:
    post:
      operationId: reload
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReloadRequest'
        required: true
      responses:
        "200":
          description: watchdog.WatchDog.Reload response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReloadResponse'
components:
  schemas:
    CertificateStatus:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/CertificateStatus.EnumCertStatus'
        certValid:
          type: boolean
        certExpiry:
          type: integer
          format: int64
    CertificateStatus.EnumCertStatus:
      type: string
      enum:
        - EnumCertStatusIgnore
        - Valid
        - Expiring
        - WrongCertificate
    DomainInfo:
      type: object
      properties:
        ipAddresses:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
    DomainItem:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        endpoints:
          type: array
          items:
            type: string
    DomainRow:
      type: object
      properties:
        info:
          $ref: '#/components/schemas/DomainInfo'
        summary:
          $ref: '#/components/schemas/DomainSummary'
        createdAt:
          type: string
          format: date-time
    DomainSummary:
      type: object
      properties:
        domain:
          $ref: '#/components/schemas/DomainItem'
        reachable:
          type: boolean
        resolvable:
          type: boolean
        certStatus:
          $ref: '#/components/schemas/CertificateStatus'
        whoIsMutated:
          type: boolean
        whoIsMutatedAt:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        httpsRedirect:
          type: boolean
    DomainWatch:
      type: object
      properties:
        name:
          type: string
        refreshInterval:
          type: integer
          format: int64
        domains:
          type: array
          items:
            $ref: '#/components/schemas/DomainItem'
    GetAllResponse:
      type: object
      properties:
        summaries:
          type: array
          items:
            $ref: '#/components/schemas/DomainSummary'
    GetDetailsResponse:
      type: object
      properties:
        summary:
          $ref: '#/components/schemas/DomainSummary'
    GetResponse:
      type: object
      properties:
        summary:
          $ref: '#/components/schemas/DomainSummary'
    HealthResponse:
      type: object
      properties:
        createdAt:
          type: integer
          format: int64
        numDomains:
          type: integer
          format: int64
        status:
          $ref: '#/components/schemas/HealthResponse.HealthStatus'
    HealthResponse.HealthStatus:
      type: string
      enum:
        - HealthStatusIgnore
        - Active
        - Error
    ReloadRequest:
      type: object
    ReloadResponse:
      type: object
