name: MyDomains
refreshinterval: 86400
domains:
  - uuid: ""
    name: www.google.com
    domainname: google.com
    endpoints:
      - https://www.google.com
      - https://www.google.com/?client=safari
  - uuid: ""
    name: mail.google.com
    endpoints:
      - https://mail.google.com
  - uuid: ""
    name: www.gmail.com
    domainname: gmail.com
    endpoints:
      - https://www.gmail.com
  - uuid: ""
    name: www.apple.com
    domainname: apple.com
    endpoints:
      - https://www.apple.com
  - uuid: ""
    name: www.dronasys.com
    domainname: dronasys.com
    endpoints:
      - https://www.dronasys.com
projects:
  - uuid: ""
    name: rustai
    org: binuud
    user: binuud
    path: Code/ai/rustai
    projecturl: "https://github.com/binuud/rustai"  
  - uuid: ""
    name: dev-tools
    org: binuud
    user: binuud
    path: Code/local/dev-tools
    projecturl: "https://github.com/binuud/dev-tools"
  - uuid: ""
    name: containers
    org: binuud
    user: binuud
    path: Code/local/containers
    projecturl: "https://github.com/binuud/containers"
  - uuid: ""
    name: watchdog
    org: binuud
    user: binuud
    path: Code/watchdog/watchdog
    projecturl: "https://github.com/binuud/watchdog"